version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - sudo yum update -y
      - sudo yum install -y php php-mysqlnd  # Install PHP dan driver MySQL (jika perlu)
      - sudo systemctl enable httpd  # Aktifkan service Apache/httpd
  pre_build:
    commands:
      - echo Pre-build phase
      # Opsional, bisa tambahkan perintah lain seperti konfigurasi
  build:
    commands:
      - echo Building the application
      - echo "No build steps needed for PHP" # Tidak ada proses build spesifik untuk PHP
      - chmod -R 777 . # Set permission agar dapat diakses public
  post_build:
    commands:
      - echo Deployment stage
      - aws s3 sync . s3://tubesdso --delete # Sync seluruh isi direktori ke S3
artifacts:
  files:
    - '**/*'  # Semua file akan disertakan sebagai artefak